version: '3.1'

services:
  postgres:
    image: postgres:14.4-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ulia_4d91
      POSTGRES_PASSWORD: pa55w0rd
      POSTGRES_DB: movie_rental

volumes:
  pg_data:
